name: DepMBT
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.9.16
    - numpy=1.23.1
    - pip=22.3.1
    - pytorch-gpu
    - pip:
      - ffmpeg-python==0.2.0
      - pip-chill==1.0.1
      - torchvision==0.13.1
      - yt-dlp==2022.9.1
      - librosa==0.9.2
      - Pillow
      - scikit-learn
      - tqdm
      - timm
      - numpy
