name: depmbt 
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.9.16
    - numpy=1.23.1
    - ffmpeg<7
    - pip=22.3.1
    - pip:
      - https://download.pytorch.org/whl/cu117/torchaudio-2.0.1%2Bcu117-cp39-cp39-linux_x86_64.whl --no-deps
      - https://download.pytorch.org/whl/cu117/torchvision-0.15.1%2Bcu117-cp39-cp39-linux_x86_64.whl --no-deps
      - https://download.pytorch.org/whl/cu117/torch-2.0.0%2Bcu117-cp39-cp39-linux_x86_64.whl
      - git+https://github.com/huggingface/pytorch-image-models.git@cb3f9c23bb31d234609711f06835724a8f0ee7da
      - facenet-pytorch==2.5.3
      - ffmpeg-python==0.2.0
      - pip-chill==1.0.1
      - yt-dlp==2022.9.1
      - librosa==0.9.2
      - Pillow
      - scikit-learn
      - tqdm
      - timm
      - numpy
      - pandas
      - torchsummary
      - matplotlib
      - lightning_utilities
      - ffprobe-python
      - ipywidgets
      - jupyterlab
      - notebook
      - nbformat
      - plotly

# /root/miniconda/envs/depmbt/lib/python3.9/site-packages/timm/layers/pos_embed.py 
# Change line 42 to 
# posemb = F.interpolate(posemb, size=new_size, mode=interpolation, align_corners=True)
# 